import { createContext } from "react";

export default createContext({
  isModeAdmin: false,
  isPannelCollapsed: false,
  panelTabIndex: "add",
  menu: [],
  basket: [],
  errors: [],
  isSubmitSuccess: false,
  isProductSelected: false,
  productSelected: {},
  inputTitleRef: {},
  newProduct: {},
  setIsModeAdmin: () => {},
  setIsPannelCollapsed: () => {},
  setPanelTabIndex: () => {},
  setIsSubmitSuccess: () => {},
  setNewProduct: () => {},
  setErrors: () => {},
  handleAdd: () => {},
  handleDelete: () => {},
  handleProductSelected: () => {},
  handleDeleteBasketProduct: () => {},
});
